# PYTHON BASICS

## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.



In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### ARRAY DIMENSIONS

In [9]:
#0D
a= np.array([40])
print(a)
print(a.ndim)   #Checking number of dimensions
#1D
b=np.array([1,2,3,4,5,6,7,8,9])
print(b)
print(b.ndim)
#2D
c=np.array([[1,2,3,4], [5,6,7,8]])
print(c)
print(c.ndim)
#3D
d=np.array([[[1,2,3,4],[1,2,9,4]],[[5,6,7,8],[5,6,7,8]]])
print(d)
print(d.ndim)
#nD
e=np.array([1,2,3,4], ndmin=5)
print(e)
print(e.ndim)

[40]
1
[1 2 3 4]
1
[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 2 3 4]
  [1 2 9 4]]

 [[5 6 7 8]
  [5 6 7 8]]]
3
[[[[[1 2 3 4]]]]]
5


#### Array indexing

In [10]:
print(b[1])
print(c[1,2])
print(d[0,1,2])

2
7
9


#### Array slicing
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start : end] 

We can also define the step, like this: [start:end:step]

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [27]:
print(b[0:3])   #including 0 but excluding 3....array position count starts from 0
print(b[-0:-2]) #slice away elements from RIGHT....1st element to to 2nd(excluding)
print(c[1,0:2]) #from 2nd dimension slice elements from 0 to 2(excluding 2 but you know it you ASSHOLE!)
print(d[0:2,1:4]) #from both index(0:2) slice elements from 1to4(1:4) OFCOURSE EXLDUING 4 you imbiscile!

[1 2 3]
[1 2]
[5 6]
[[[1 2 9 4]]

 [[5 6 7 8]]]
[1 3]


In [28]:
?????????print(b[0:8:2]) #STEP is the 3rd argument which skips elements (n-1) here n is 2 => (2-1) = 1 => 1 element skipping

Object `???????print(b[0:8:2]) #STEP is the 3rd argument which skips elements (n-1) here n is 2 => (2-1) = 1 => 1 element skipping` not found.
